"""changed user-uid to user_id in  books

Revision ID: 7fce99af6f7d
Revises: 5484896eb566
Create Date: 2025-03-25 23:35:25.132189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fce99af6f7d'
down_revision: Union[str, None] = '5484896eb566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.drop_constraint('books_user_uid_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['id'])
    op.drop_column('books', 'user_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_user_uid_fkey', 'books', 'users', ['user_uid'], ['id'])
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
